version: "3.9"

services:
  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_network
    volumes:
      - redis:/data

networks:
  my_network:
    driver: bridge

volumes:
  redis:
    driver: local