# Generated by Django 4.2.5 on 2023-09-13 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionmodel",
            name="tx_id",
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="information",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="transactionmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
